-- CreateEnum
CREATE TYPE "Role" AS ENUM ('OWNER', 'OFFICIAL', 'VERIFIED', 'MEMBER');

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;
ALTER TABLE "User" ALTER COLUMN "role" TYPE "Role" USING "role"::"Role";
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'MEMBER';
